DROP TYPE accept_status CASCADE;
DROP TYPE user_spec CASCADE;
DROP TYPE message_type CASCADE;
DROP TYPE component_condition CASCADE;
DROP TYPE component_types CASCADE;
DROP TYPE tire_types CASCADE;
DROP TYPE transfers CASCADE;
DROP TABLE photos CASCADE;
DROP TABLE users CASCADE;
DROP TABLE teams CASCADE;
DROP TABLE team_members CASCADE;
DROP TABLE sponsors CASCADE;
DROP TABLE sponsoring CASCADE;
DROP TABLE seasons CASCADE;
DROP TABLE world_cup_result CASCADE;
DROP TABLE constr_cup_result CASCADE;
DROP TABLE championships CASCADE;
DROP TABLE cars CASCADE;
DROP TABLE piloting CASCADE;
DROP TABLE races CASCADE;
DROP TABLE chats CASCADE;
DROP TABLE user_chat CASCADE;
DROP TABLE messages CASCADE;
DROP TABLE component_changes CASCADE;
DROP TABLE race_registration CASCADE;
DROP TABLE race_results CASCADE;
DROP TABLE pit_stop_places CASCADE;
DROP TABLE pit_stop_service CASCADE;
DROP TABLE pit_stop_repair CASCADE;
DROP TABLE pilot_change CASCADE;
DROP TABLE pit_stop_transfer CASCADE;
DROP TABLE engine_storage CASCADE;
DROP TABLE carcase_storage CASCADE ;
DROP TABLE chassis_storage CASCADE ;
DROP TABLE electronics_storage CASCADE ;